config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about'

  namespace :public do
    resources :customers, only: [:index,:show]
    resources :games, only: [:index,:show] do
      resources :reviews, only: [:new,:create,:show,:edit,:update,:destroy] do
        resources :comments, only: [:create,:edit,:update,:destroy]
        resources :nices, only: [:create,:destroy]
      end
    end
  end

  namespace :admin do
    resources :games, only: [:index,:create,:show,:edit,:update,:destroy]
  end

  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :customers, skip: [:passwords], controllers: {
        sessions: 'public/sessions',
        registrations: 'public/registrations',
      }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
        sessions: 'admin/sessions'
      }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :review

  validates :comment_body, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #validates :image, presence: true

  has_many :reviews
  has_many :comments
  has_many :nices

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.nick_name = "ゲスト"
      customer.id = 999
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/game.rb
class Game < ApplicationRecord
  enum player: { 一人用:0, 二人用:1, 三人用:2, 四人用:3 }
  enum genre: { 音楽:0, ロールプレイング:1, アクション:2, テーブル:3, パズル:4, シューティング:5 }

  has_one_attached :image
  has_many :reviews, dependent: :destroy


  def self.search(search, player, genre)
    if search
       where(['title LIKE ?', "%#{search}%"]).where(player: player).where(genre: genre)
    else
       all #全て表示させる
    end
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/nice.rb
class Nice < ApplicationRecord
  belongs_to :customer
  belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord
  has_one_attached :image
  belongs_to :game
  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :nices, dependent: :destroy

  validates :title, {presence: true, length:{maximum:20}}
  validates :body, presence: true

  # niceされていればtrue, それ以外はfalse
  def nice_by?(customer)
    customer_ids = nices.map {|nice| nice.customer.id }
    customer_ids.include?(customer.id)
  end
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < ApplicationController
  def index
    @game = Game.new
    @games = Game.page(params[:page]).per(7)
  end

  def create
    @game = Game.new(game_params)
    @game.save
      redirect_to admin_games_path
  end

  def show
    @game = Game.find(params[:id])
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])
    @game.update(game_params)
      redirect_to admin_game_path(@game.id)
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to admin_games_path
  end

  private
  def game_params
    params.require(:game).permit(:image, :title, :player, :genre)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/game_title_helper.rb
module Admin::GameTitleHelper
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/admin/guests_helper.rb
module Admin::GuestsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers/customer_helper.rb
module Customers::CustomerHelper
end

app/helpers/customers/customers_helper.rb
module Customers::CustomersHelper
end

app/helpers/customers/guests_helper.rb
module Customers::GuestsHelper
end

app/helpers/customers/posts_helper.rb
module Customers::PostsHelper
end

app/helpers/customers/users_helper.rb
module Customers::UsersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/games/edit.html.erb
<div class="col-10 offset-1">
  <div class="pt-2">
    <strong>
      <%= link_to "ゲーム詳細に戻る", admin_game_path(@game.id) %>
    </strong>
  </div>
  <div class="row justify-content-center">
    <h1 class="py-2"><strong>ゲーム情報編集</strong></h1>
  </div>
  <div class="row justify-content-center">
    <%= form_with model:@game, url: admin_game_path do |f| %>
      <div>
        <h3>画像</h3>
        <%= f.file_field :image, accept: "image/*" %>
      </div>
      <div>
        <h3 class="pt-3">タイトル</h3>
        <%= f.text_field :title %>
      </div>
      <div>
        <h3 class="pt-3">人数</h3>
          <%= f.radio_button :player, Game.players.key(0) %><%= f.label:player,'一人用', value: Game.players.key(0) %>
          <%= f.radio_button :player, Game.players.key(1) %><%= f.label:player,'二人用', value: Game.players.key(1) %>
          <%= f.radio_button :player, Game.players.key(2) %><%= f.label:player,'三人用', value: Game.players.key(2) %>
          <%= f.radio_button :player, Game.players.key(3) %><%= f.label:player,'四人用', value: Game.players.key(3) %>
      </div>
      <div>
        <h3 class="pt-3">ジャンル</h3>
        <%= f.radio_button :genre, Game.genres.key(0) %><%= f.label:genre,'音楽', value: Game.genres.key(0) %><br>
        <%= f.radio_button :genre, Game.genres.key(1) %><%= f.label:genre,'ロールプレイング', value: Game.genres.key(1) %><br>
        <%= f.radio_button :genre, Game.genres.key(2) %><%= f.label:genre,'アクション', value: Game.genres.key(2) %><br>
        <%= f.radio_button :genre, Game.genres.key(3) %><%= f.label:genre,'テーブル', value: Game.genres.key(3) %><br>
        <%= f.radio_button :genre, Game.genres.key(4) %><%= f.label:genre,'パズル', value: Game.genres.key(4) %><br>
        <%= f.radio_button :genre, Game.genres.key(5) %><%= f.label:genre,'シューティング', value: Game.genres.key(5) %><br>
      </div>
      <div class="text-center py-3">
        <%= f.submit "更新する" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/games/index.html.erb
<div class="col-10 offset-1">
  <div class="row justify-content-center">
    <h1 class="py-2"><strong>ゲーム登録・一覧</strong></h1>
  </div>
</div>

<div class="col-4">
   <div class="row justify-content-center">
    <%= form_with model: @game, url: admin_games_path do |f| %>
      <div>
        <h3>画像</h3>
        <%= f.file_field :image, accept: "image/*" %>
      </div>
      <div>
        <h3 class="pt-3">タイトル</h3>
        <%= f.text_field :title %>
      </div>
      <div>
        <h3 class="pt-3">人数</h3>
          <%= f.radio_button :player, Game.players.key(0) %><%= f.label:player,'一人用', value: Game.players.key(0) %>
          <%= f.radio_button :player, Game.players.key(1) %><%= f.label:player,'二人用', value: Game.players.key(1) %>
          <%= f.radio_button :player, Game.players.key(2) %><%= f.label:player,'三人用', value: Game.players.key(2) %>
          <%= f.radio_button :player, Game.players.key(3) %><%= f.label:player,'四人用', value: Game.players.key(3) %>
      </div>
      <div>
        <h3 class="pt-3">ジャンル</h3>
        <%= f.radio_button :genre, Game.genres.key(0) %><%= f.label:genre,'音楽', value: Game.genres.key(0) %><br>
        <%= f.radio_button :genre, Game.genres.key(1) %><%= f.label:genre,'ロールプレイング', value: Game.genres.key(1) %><br>
        <%= f.radio_button :genre, Game.genres.key(2) %><%= f.label:genre,'アクション', value: Game.genres.key(2) %><br>
        <%= f.radio_button :genre, Game.genres.key(3) %><%= f.label:genre,'テーブル', value: Game.genres.key(3) %><br>
        <%= f.radio_button :genre, Game.genres.key(4) %><%= f.label:genre,'パズル', value: Game.genres.key(4) %><br>
        <%= f.radio_button :genre, Game.genres.key(5) %><%= f.label:genre,'シューティング', value: Game.genres.key(5) %><br>
      </div>
      <div class="text-center py-3">
        <%= f.submit "新規登録" %>
      </div>
    <% end %>
  </div>
</div>


<div class="col-7">
  <% @games.each do |game| %>
    <div class="card">
      <div class="card-body">
        <%= link_to game.title, admin_game_path(game.id) %>
        <%= game.player %>
        <%= game.genre %>
      </div>
    </div>
  <% end %>
  <div class="row justify-content-center py-5">
    <%= paginate @games, theme: 'twitter-bootstrap-4' %>
  </div>
</div>

app/views/admin/games/show.html.erb
<div class="col-10 offset-1">
  <div class="pt-2">
    <strong>
      <%= link_to "ゲーム登録・一覧に戻る", admin_games_path %>
    </strong>
  </div>
  <div class="row justify-content-center">
    <h1 class="py-2"><strong>ゲーム詳細</strong></h1>
  </div>
  <div class="row justify-content-center">
    <div class="pr-5 mr-5">
      <%= image_tag @game.get_image, size: "300x300"%>
    </div>
    <h3>
      <%= @game.title %><br>
      <%= @game.player %><br>
      <%= @game.genre %>
    </h3>
  </div>
  <div class="row justify-content-center pt-5">
    <%= link_to "編集画面へ", edit_admin_game_path, class: "btn btn-success" %>
  </div>
  <div class="row justify-content-center pt-3">
    <%= link_to "削除", admin_game_path(@game.id), method: :delete, class: "btn btn-danger" %>
  </div>
</div>