config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'homes/about'

  namespace :public do
    resources :customers, only: [:index,:show]
    resources :games, only: [:index,:show] do
      resources :reviews, only: [:new,:create,:show,:edit,:update,:destroy] do
        resources :comments, only: [:create,:edit,:update,:destroy]
        resources :nices, only: [:create,:destroy]
      end
    end
  end

  namespace :admin do
    resources :games, only: [:index,:create,:show,:edit,:update,:destroy]
  end

  devise_scope :customer do
    post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  devise_for :customers, skip: [:passwords], controllers: {
        sessions: 'public/sessions',
        registrations: 'public/registrations',
      }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
        sessions: 'admin/sessions'
      }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :review

  validates :comment_body, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #validates :image, presence: true

  has_many :reviews
  has_many :comments
  has_many :nices

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.nick_name = "ゲスト"
      customer.id = 999
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
    end
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/game.rb
class Game < ApplicationRecord
  enum player: { 一人用:0, 二人用:1, 三人用:2, 四人用:3 }
  enum genre: { 音楽:0, ロールプレイング:1, アクション:2, テーブル:3, パズル:4, シューティング:5 }

  has_one_attached :image
  has_many :reviews, dependent: :destroy


  def self.search(search, player, genre)
    if search
       where(['title LIKE ?', "%#{search}%"]).where(player: player).where(genre: genre)
    else
       all #全て表示させる
    end
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/nice.rb
class Nice < ApplicationRecord
  belongs_to :customer
  belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord
  has_one_attached :image
  belongs_to :game
  belongs_to :customer
  has_many :comments, dependent: :destroy
  has_many :nices, dependent: :destroy

  validates :title, {presence: true, length:{maximum:20}}
  validates :body, presence: true

  # niceされていればtrue, それ以外はfalse
  def nice_by?(customer)
    customer_ids = nices.map {|nice| nice.customer.id }
    customer_ids.include?(customer.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    root_path
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/admin/game_title_helper.rb
module Admin::GameTitleHelper
end

app/helpers/admin/games_helper.rb
module Admin::GamesHelper
end

app/helpers/admin/guests_helper.rb
module Admin::GuestsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers/guests_helper.rb
module Customers::GuestsHelper
end

app/helpers/customers/posts_helper.rb
module Customers::PostsHelper
end

app/helpers/customers/users_helper.rb
module Customers::UsersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-info">
    <a class="navbar-brand" href="/"><h1>GAME_REVIEW</h1></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <% if customer_signed_in? %>
            <li><strong><%= link_to "ゲーム一覧", public_games_path, class:"nav-link" %></strong></li>
            <li><strong><%= link_to "会員一覧", public_customers_path, class:"nav-link" %></strong></li>
            <li><strong><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"nav-link" %></strong></li>
          <% elsif admin_signed_in? %>
            <li><strong><%= link_to "ゲーム登録・一覧", admin_games_path, class:"nav-link" %></strong></li>
            <li><strong><%= link_to "adminログアウト", destroy_admin_session_path, method: :delete, class:"nav-link" %></strong></li>
          <% else %>
            <li><strong><%= link_to "about", homes_about_path, class:"nav-link" %></strong></li>
            <li><strong><%= link_to "新規登録", new_customer_registration_path, class:"nav-link" %></strong></li>
            <li><strong><%= link_to "ログイン", new_customer_session_path, class:"nav-link" %></strong></li>
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameReview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container-fluid">
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <script type="text/javascript">
      $(document).ready(function () {
        if ($('[data-toggle="tooltip"]')) {
          // $('[data-toggle="tooltip"]').tooltip();
        }
      });
    </script>
  </body>
</html>